#!/usr/bin/env python3
"""Render repository documentation as an independently navigable GitHub Pages site."""
import argparse
import html
import os
from pathlib import Path
import re
import shutil
from html.parser import HTMLParser
from urllib.parse import unquote, urlsplit
import xml.etree.ElementTree as ET

import markdown

ROOT = Path(__file__).resolve().parents[1]
REPO = 'https://github.com/cicarulez/PulseDeck'
NAV = [('Get started', 'docs/getting-started.html'), ('Gallery', 'docs/gallery.html'),
       ('Contribute', 'CONTRIBUTING.html'), ('Roadmap', 'docs/roadmap.html'),
       ('Italiano', 'docs/README.it.html')]


def relative(target, page):
    return os.path.relpath(target, page.parent).replace(os.sep, '/')


def render(output):
    if output.exists():
        if output != ROOT / 'artifacts/site' and not (output / '.pulsedeck-site').is_file():
            raise SystemExit('Refusing to replace an existing directory not generated by PulseDeck.')
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)
    (output / '.pulsedeck-site').write_text('Generated by scripts/build-site.py\n')
    shutil.copytree(ROOT / 'site', output, dirs_exist_ok=True)
    shutil.copytree(ROOT / 'docs/images', output / 'docs/images', dirs_exist_ok=True)
    sources = sorted({ROOT / name for name in ('README.md', 'CONTRIBUTING.md',
                     'CODE_OF_CONDUCT.md', 'SECURITY.md', 'THIRD-PARTY-NOTICES.md')} |
                     set((ROOT / 'docs').rglob('*.md')) |
                     set((ROOT / 'tools').glob('*/README.md')))
    pages = {p.relative_to(ROOT): p.relative_to(ROOT).with_suffix('.html') for p in sources}
    version = ET.parse(ROOT / 'apps/agent/PulseDeck.Agent.csproj').findtext('.//Version')
    template = (ROOT / 'site/document.html').read_text()
    for source in sources:
        source_path = source.relative_to(ROOT)
        page = pages[source_path]
        md = markdown.Markdown(extensions=['tables', 'fenced_code', 'toc', 'sane_lists'])
        content = md.convert(source.read_text())
        title_match = re.search(r'<h1[^>]*>(.*?)</h1>', content, re.S)
        title = re.sub('<[^>]+>', '', title_match.group(1)) if title_match else source.stem

        def link(match):
            attr, quote, value = match.groups()
            parts = urlsplit(html.unescape(value))
            if parts.scheme or parts.netloc or not parts.path:
                return match.group(0)
            target = Path(os.path.normpath(source_path.parent / unquote(parts.path)))
            if not (ROOT / target).exists() or not (ROOT / target).resolve().is_relative_to(ROOT):
                raise SystemExit(f'{source_path}: missing or invalid source link {value}')
            if target in pages:
                href = relative(pages[target], page)
            elif target.parts[:2] == ('docs', 'images') and (ROOT / target).is_file():
                href = relative(target, page)
            else:
                kind = 'tree' if (ROOT / target).is_dir() else 'blob'
                href = f'{REPO}/{kind}/main/{target.as_posix()}'
            if parts.query:
                href += '?' + parts.query
            if parts.fragment:
                href += '#' + parts.fragment
            return f'{attr}={quote}{html.escape(href, quote=True)}{quote}'

        content = re.sub(r'\b(href|src)=([\"\'])(.*?)\2', link, content)
        nav = ''.join(f'<a href="{relative(Path(dest), page)}"' +
                      (' aria-current="page"' if Path(dest) == page else '') +
                      f'>{label}</a>' for label, dest in NAV)
        replacements = {'TITLE': html.escape(title), 'CONTENT': content, 'TOC': md.toc,
                        'NAV': nav, 'HOME': relative(Path('index.html'), page),
                        'CSS': relative(Path('styles.css'), page),
                        'PRIVACY': relative(Path('privacy.html'), page),
                        'SOURCE': f'{REPO}/blob/main/{source_path.as_posix()}',
                        'LANG': 'it' if source.name.endswith('.it.md') else 'en',
                        'VERSION': version}
        document = template
        for key, value in replacements.items():
            document = document.replace('{{' + key + '}}', value)
        destination = output / page
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(document)
    # This file is a build template, not a public page.
    (output / 'document.html').unlink()
    index = output / 'index.html'
    index.write_text(index.read_text().replace('{{VERSION}}', version))
    check_links(output)
    print(f'Built {len(pages) + 2} HTML pages in {output} (v{version}); local links verified.')


class Links(HTMLParser):
    def __init__(self):
        super().__init__()
        self.links = []
        self.ids = set()

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if 'id' in attrs:
            self.ids.add(attrs['id'])
        for key in ('href', 'src'):
            if key in attrs:
                self.links.append(attrs[key])


def check_links(output):
    documents = {}
    for page in output.rglob('*.html'):
        parser = Links()
        parser.feed(page.read_text())
        documents[page.resolve()] = parser
    errors = []
    for page, parser in documents.items():
        for value in parser.links:
            parts = urlsplit(value)
            if parts.scheme or parts.netloc:
                continue
            dest = (page.parent / unquote(parts.path)).resolve() if parts.path else page
            if not dest.is_relative_to(output.resolve()) or not dest.is_file():
                errors.append(f'{page.relative_to(output.resolve())}: missing {value}')
            elif parts.fragment and dest in documents and unquote(parts.fragment) not in documents[dest].ids:
                errors.append(f'{page.relative_to(output.resolve())}: missing anchor {value}')
    if errors:
        raise SystemExit('\n'.join(errors))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=ROOT / 'artifacts/site')
    args = parser.parse_args()
    render(args.output.resolve())
